### ISSUE TITLE
link WzComparerR2 api

### ISSUE THREAD

**Issue by leecs0503** [leecs0503/maple-cody-recommendation-system#2]
[위컴알 api](https://github.com/KENNYSOFT/WzComparerR2/releases)를 활용해서 메이플 캐릭터를 코디를 시뮬레이션 하는 스크립트 작성

**Comment by kig9981** [comment]
WzCompareR2 분석

WzCompareR2 : 메인 프로그램 코드가 있는 위치

WzCompareR2\Program.cs : 프로그램의 메인 엔트리(메인함수)
WzCompareR2\MainForm.cs : 프로그램의 MainForm
 - private void openWz(string wzFilePath) : 메이플스토리의 wz파일을 여는 함수. 여기서 원하는 데이터파일을 불러온다. 열면 openedWz list에 추가
WzCompareR2.WzLib\Wz_Structure.cs : wz확장자파일을 읽고 관리할 수 있음.
WzCompareR2.WzLib\Wz_File.cs : wz확장자 파일 내부 데이터 개별 파일을 읽고 관리할 수 있음
WzCompareR2.WzLib\Wz_Type.cs : wz파일 내부 파일들의 타입

WzCompareR2.Avatar\AvatarCanvas.cs : 아바타를 직접 그려줌(핵심)
 - public string ActionName : 동작 이름 설정, stand1 또는 stand2
 - public string EmotionName : 표정 이름 설정, default
 - public AvatarPart AddPart(Wz_Node imgNode) : Wz파일에서 이미지를 불러오면 아바타에 해당 파츠를 추가해준다.
 - public BitmapOrigin DrawFrame(Bone bone) : 해당되는 이미지를 그려준다.
 - public Bone CreateFrame(int bodyFrame, int faceFrame, int tamingFrame) : bodyframe, faceprame, tamingframe을 토대로 draw를 할수있는 actionframe을 생성한다. 0 0 0 고정(아마도)




WzCompareR2.Avatar\AvatarAction.cs : 아바타의 행동을 저장. stand1이나 stand2를 고르는 것이 맞는거같다.
WzCompareR2.Avatar\UI\AvatarForm.cs : 아바타 형태를 불러오는(?) form..?
 - private void LoadCode(string code, int loadType) : wz파일 내부의 아이템코드를 받아서 그에 맞는 아바타를 로드하는 함수.(중요!)
 - findNodeByXXXID
 - private void OnNewPartAdded(AvatarPart part) : LoadCode, LoadPart함수 등에서 이미지를 로드한 뒤에 실제로 아바타에 적용시켜주는 함수
 - private bool AvatarInit() : avatarcanvas 객체를 초기화하는 함수 LoadZ, LoadActions, LoadEmotions를 할 필요가 있음

**Comment by kig9981** [comment]
믹스염색에 대한 추가정보.

머리에 대한 기본 정보 아이템코드 (XX색 OO머리) + (추가할 색 코드) * (비율)
색코드 : 검은색(0) 빨간색(1) 주황색(2) 노란색(3) 초록색(4) 파란색(5) 보라색(6) 갈색(7)
예) 검은색 토벤 머리(아이템코드 30000) + 갈색 30 믹스염색 -> 30000+7*30

**Comment by kig9981** [comment]
- [x] 기본 asp.net 기반 rest api 켜보기
- [ ] [공식 문서](https://learn.microsoft.com/ko-kr/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio) MVC 파악
- [x] 아래 형식을 받는 GET /items을 구현
```
input: 없음
output: {
   "상의": [{번호, 아이템이름}..],
   "하의": [{번호, 아이템이름}..],
   "무기": [{번호, 아이템이름}..],
   ...
}
```
- [ ] 아래 형식을 받는 POST형식 /MapleCodyImage 구현
```
input
{
    "bs64": "~~~~~~"
}
output
{
    "model_vector": [],
    "item_names": [],
}
```
