### ISSUE TITLE
make base train data using crawling script

### ISSUE THREAD

**Issue by leecs0503** [leecs0503/maple-cody-recommendation-system#4]
#1 에서 작성한 스크립트를 이용해 테스트 데이터를 만드는 작업
각 유저에 대해 최근 6개의 이미지를 추출해 저장하고, json파일을 생성
annotation은 json format
이름, 랭킹, 저장한 6개 코디의 이미지 uri로 구성

**Comment by leecs0503** [comment]
이후 google drive에 저장 후 공유

**Comment by leecs0503** [comment]
## work flow
 - [ ] 이미지 추출 및 json파일 구성
 - [ ] google drive에 작성

**Comment by dbrudghks333** [comment]
이미지 추출 및 json 파일 google drive 주소 :
https://drive.google.com/drive/u/0/folders/1_E9kLzyVleDgTvepEbw0Og7CMvge9JHi
